sudo: required

language: node_js

services:
    - docker

before_install:
  - docker build -t fetcher-test ./fetcher
  - docker run -d --name app fetcher-test
  - docker ps -a

script:
  - docker exec app npm test

after_script:
  - docker rm -f app
