sudo: required

language: node_js

services:
    - docker

before_install:
  - docker build -t web-test ./web
  - docker run -d --name app web-test
  - docker ps -a

script:
  - docker exec app npm test

after_script:
  - docker rm -f app
