version: '2'
services:
  fetcher:
    build: ./fetcher
    environment:
      DB_USER: ${FETCHER_DB_NAME}
      DB_NAME: ${FETCHER_DB_USER}
      DB_PASSWORD: ${FETCHER_DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    links:
      - db
    ports:
      - "8081:8081"
  web:
    build: ./web
    environment:
      DB_USER: ${WEB_DB_NAME}
      DB_NAME: ${WEB_DB_USER}
      DB_PASSWORD: ${WEB_DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    links:
      - db
    ports:
      - "8082:8082"
  ai:
    restart: always
    build: ./ai
    environment:
      DB_USER: ${AI_DB_NAME}
      DB_NAME: ${AI_DB_USER}
      DB_PASSWORD: ${AI_DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    expose:
      - "8000"
    links:
      - db:db
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      volumes:
        - /www/static
      volumes_from:
        - ai
      links:
        - ai:ai
  db:
    build:
      context: ./db
      args:
        AI_DB_NAME: ${AI_DB_NAME}
        AI_DB_USER: ${AI_DB_USER}
        AI_DB_PASSWORD: ${AI_DB_PASSWORD}
        WEB_DB_USER: ${WEB_DB_NAME}
        WEB_DB_NAME: ${WEB_DB_USER}
        WEB_DB_PASSWORD: ${WEB_DB_PASSWORD}
        FETCHER_DB_NAME: ${FETCHER_DB_NAME}
        FETCHER_DB_USER: ${FETCHER_DB_USER}
        FETCHER_DB_PASSWORD: ${FETCHER_DB_PASSWORD}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
