version: '2'
services:
  fetcher:
    build: ./fetcher
    environment:
      DB_USER: ${POSTGRES_USER},
      DB_NAME: ${POSTGRES_DB},
      DB_PASSWORD: ${POSTGRES_PASSWORD},
      DB_HOST: db,
      DB_PORT: 5432,
    links:
      - db
    ports:
      - "8081:8081"
  db:
    image: library/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/pgdata:/pgdata
      - ./db/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    ports:
      - "5432:5432"
